language: python
python:
  - "3.6"      
  - "3.7"
# command to install dependencies
services:
  - docker
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
# command to run tests
script: 
  - docker-compose build
  - docker-compose up -d
 
after_success:
  - docker build .
  - docker tag server fortotal/server_travis
  - docker push fortotal/server_travis
  
